# I found it hard to deal with the environment for the fact that
#  the version of 'carvekit' conflicts to toch==1.12.0

name: 3DFuse

channels:
  - pytorch
  - defaults

dependencies:
  - python = 3.8.0
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.22.4
  - pip:
    - gradio
    - albumentations==1.3.0
    - opencv-contrib-python==4.3.0.36
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.5.0
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit==1.12.1
    - einops==0.3.0
    - transformers
    - diffusers==0.11.1
    - webdataset==0.2.5
    - kornia==0.6
    - open_clip_torch==2.0.2
    - invisible-watermark>=0.1.5
    - streamlit-drawable-canvas==0.8.0
    - torchmetrics==0.6.0
    - timm==0.6.12
    - addict==2.4.0
    - yapf==0.32.0
    - prettytable==3.6.0
    - safetensors==0.2.7
    - basicsr==1.4.2
    - pydantic
    - click
    - easydict
    - tabulate
    - plotly
    - accelerate
    - carvekit